name-template: 'noipy v$RESOLVED_VERSION (date: $CURRENT_DATE)'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
  - title: '🧹 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '🔧 Refactoring'
    labels:
      - 'refactor'
      - 'refactoring'
  - title: '⚡ Performance'
    labels:
      - 'performance'
  - title: '🧪 Testing'
    labels:
      - 'test'
      - 'testing'
  - title: '🔒 Security'
    labels:
      - 'security'
  - title: '💥 Breaking Changes'
    labels:
      - 'breaking'
      - 'breaking-change'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
autolabeler:
  - label: 'chore'
    files:
      - '*.md'
      - '*.rst'
      - '*.yml'
      - '*.yaml'
      - '*.toml'
      - '*.ini'
      - '*.cfg'
    branch:
      - '/docs{0,1}\/.+/'
      - '/maintenance\/.+/'
  - label: 'fix'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
      - '/bugfix/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
  - label: 'docs'
    files:
      - '*.md'
      - '*.rst'
      - '/docs/'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'refactor'
    branch:
      - '/refactor\/.+/'
      - '/refact\/.+/'
  - label: 'security'
    branch:
      - '/security\/.+/'
  - label: 'test'
    branch:
      - '/test\/.+/'
replacers:
  - search: '/CVE-(\d{4})-(\d+)/g'
    replace: 'https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-$1-$2'
  - search: '/(https?:\/\/github\.com\/pv8\/noipy\/pull\/)(\d+)/g'
    replace: 'https://github.com/pv8/noipy/pull/$2'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
      - 'enhancement'
  patch:
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  default: patch
template: |
  ## 🚀 Release $RESOLVED_VERSION

  $CHANGES

  ## ↔️ Changelog
  - [`$PREVIOUS_TAG...v$RESOLVED_VERSION`](https://github.com/pv8/noipy/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION)

  ---
  *This release was automatically generated by [Release Drafter](https://github.com/release-drafter/release-drafter)*